# @package __global__
#
# Task 4: Curriculum Learning - Short Sequence Variant (10s)
#
# Start training with shorter sequences to:
# - Speed up initial convergence
# - Reduce memory requirements
# - Establish stable gradients before long sequences
#
# After N epochs with good CE/PPL slope, switch to longer segments
#
# Usage:
#   python -m dora run solver=musicgen/musicgen_base_32khz \
#       dset=audio/all_data \
#       +curriculum/short_10s

defaults:
  - /solver/musicgen/musicgen_base_32khz
  - _self_

# Short sequence curriculum settings
dataset:
  segment_duration: 10    # Reduced from 30-60s
  batch_size: 128         # Can increase due to shorter sequences
  min_segment_ratio: 0.8

# Adjusted optimization for curriculum
optim:
  epochs: 50              # Curriculum phase epochs
  updates_per_epoch: 2000 # Shorter updates for faster iteration
  lr: 1e-4
  max_norm: 1.0

# More frequent checkpoints during curriculum
checkpoint:
  save_every: 1000
  keep_last: 5

# More frequent evaluation to track progress
evaluate:
  every: 5

generate:
  every: 10
  lm:
    gen_duration: 10      # Match segment duration
